/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TentangRouteImport } from './routes/tentang'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as OwnerRouteImport } from './routes/owner'
import { Route as MasukRouteImport } from './routes/masuk'
import { Route as LengkapiProfilRouteImport } from './routes/lengkapi-profil'
import { Route as LanjutRouteImport } from './routes/lanjut'
import { Route as KeranjangRouteImport } from './routes/keranjang'
import { Route as DokterRouteImport } from './routes/dokter'
import { Route as BookingRouteImport } from './routes/booking'
import { Route as AkunRouteImport } from './routes/akun'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TreatmentIndexRouteImport } from './routes/treatment.index'
import { Route as OwnerIndexRouteImport } from './routes/owner.index'
import { Route as DokterIndexRouteImport } from './routes/dokter.index'
import { Route as AkunIndexRouteImport } from './routes/akun.index'
import { Route as TreatmentIdRouteImport } from './routes/treatment.$id'
import { Route as OwnerVoucherRouteImport } from './routes/owner.voucher'
import { Route as OwnerTreatmentRouteImport } from './routes/owner.treatment'
import { Route as OwnerTransaksiRouteImport } from './routes/owner.transaksi'
import { Route as OwnerProfilRouteImport } from './routes/owner.profil'
import { Route as OwnerPrivilegeRouteImport } from './routes/owner.privilege'
import { Route as OwnerPosRouteImport } from './routes/owner.pos'
import { Route as OwnerLaporanRouteImport } from './routes/owner.laporan'
import { Route as OwnerJadwalRouteImport } from './routes/owner.jadwal'
import { Route as OwnerBeauticianRouteImport } from './routes/owner.beautician'
import { Route as OwnerAkunRouteImport } from './routes/owner.akun'
import { Route as KwitansiIdRouteImport } from './routes/kwitansi.$id'
import { Route as DokterProfilRouteImport } from './routes/dokter.profil'
import { Route as DokterJadwalRouteImport } from './routes/dokter.jadwal'
import { Route as ApiTreatmentImageRouteImport } from './routes/api/treatment-image'
import { Route as ApiSeedRouteImport } from './routes/api/seed'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as ApiBootstrapOwnerRouteImport } from './routes/api/bootstrap-owner'
import { Route as AkunProfilRouteImport } from './routes/akun.profil'
import { Route as AkunPrivilegeRouteImport } from './routes/akun.privilege'
import { Route as OwnerPasienIndexRouteImport } from './routes/owner.pasien.index'
import { Route as OwnerDokterIndexRouteImport } from './routes/owner.dokter.index'
import { Route as DokterPasienIndexRouteImport } from './routes/dokter.pasien.index'
import { Route as AkunBookingIndexRouteImport } from './routes/akun.booking.index'
import { Route as OwnerPasienIdRouteImport } from './routes/owner.pasien.$id'
import { Route as OwnerDokterIdRouteImport } from './routes/owner.dokter.$id'
import { Route as DokterPasienIdRouteImport } from './routes/dokter.pasien.$id'
import { Route as ApiMidtransNotificationRouteImport } from './routes/api/midtrans/notification'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as AkunBookingIdRouteImport } from './routes/akun.booking.$id'

const TentangRoute = TentangRouteImport.update({
  id: '/tentang',
  path: '/tentang',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnerRoute = OwnerRouteImport.update({
  id: '/owner',
  path: '/owner',
  getParentRoute: () => rootRouteImport,
} as any)
const MasukRoute = MasukRouteImport.update({
  id: '/masuk',
  path: '/masuk',
  getParentRoute: () => rootRouteImport,
} as any)
const LengkapiProfilRoute = LengkapiProfilRouteImport.update({
  id: '/lengkapi-profil',
  path: '/lengkapi-profil',
  getParentRoute: () => rootRouteImport,
} as any)
const LanjutRoute = LanjutRouteImport.update({
  id: '/lanjut',
  path: '/lanjut',
  getParentRoute: () => rootRouteImport,
} as any)
const KeranjangRoute = KeranjangRouteImport.update({
  id: '/keranjang',
  path: '/keranjang',
  getParentRoute: () => rootRouteImport,
} as any)
const DokterRoute = DokterRouteImport.update({
  id: '/dokter',
  path: '/dokter',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingRoute = BookingRouteImport.update({
  id: '/booking',
  path: '/booking',
  getParentRoute: () => rootRouteImport,
} as any)
const AkunRoute = AkunRouteImport.update({
  id: '/akun',
  path: '/akun',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TreatmentIndexRoute = TreatmentIndexRouteImport.update({
  id: '/treatment/',
  path: '/treatment/',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnerIndexRoute = OwnerIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OwnerRoute,
} as any)
const DokterIndexRoute = DokterIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DokterRoute,
} as any)
const AkunIndexRoute = AkunIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AkunRoute,
} as any)
const TreatmentIdRoute = TreatmentIdRouteImport.update({
  id: '/treatment/$id',
  path: '/treatment/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnerVoucherRoute = OwnerVoucherRouteImport.update({
  id: '/voucher',
  path: '/voucher',
  getParentRoute: () => OwnerRoute,
} as any)
const OwnerTreatmentRoute = OwnerTreatmentRouteImport.update({
  id: '/treatment',
  path: '/treatment',
  getParentRoute: () => OwnerRoute,
} as any)
const OwnerTransaksiRoute = OwnerTransaksiRouteImport.update({
  id: '/transaksi',
  path: '/transaksi',
  getParentRoute: () => OwnerRoute,
} as any)
const OwnerProfilRoute = OwnerProfilRouteImport.update({
  id: '/profil',
  path: '/profil',
  getParentRoute: () => OwnerRoute,
} as any)
const OwnerPrivilegeRoute = OwnerPrivilegeRouteImport.update({
  id: '/privilege',
  path: '/privilege',
  getParentRoute: () => OwnerRoute,
} as any)
const OwnerPosRoute = OwnerPosRouteImport.update({
  id: '/pos',
  path: '/pos',
  getParentRoute: () => OwnerRoute,
} as any)
const OwnerLaporanRoute = OwnerLaporanRouteImport.update({
  id: '/laporan',
  path: '/laporan',
  getParentRoute: () => OwnerRoute,
} as any)
const OwnerJadwalRoute = OwnerJadwalRouteImport.update({
  id: '/jadwal',
  path: '/jadwal',
  getParentRoute: () => OwnerRoute,
} as any)
const OwnerBeauticianRoute = OwnerBeauticianRouteImport.update({
  id: '/beautician',
  path: '/beautician',
  getParentRoute: () => OwnerRoute,
} as any)
const OwnerAkunRoute = OwnerAkunRouteImport.update({
  id: '/akun',
  path: '/akun',
  getParentRoute: () => OwnerRoute,
} as any)
const KwitansiIdRoute = KwitansiIdRouteImport.update({
  id: '/kwitansi/$id',
  path: '/kwitansi/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const DokterProfilRoute = DokterProfilRouteImport.update({
  id: '/profil',
  path: '/profil',
  getParentRoute: () => DokterRoute,
} as any)
const DokterJadwalRoute = DokterJadwalRouteImport.update({
  id: '/jadwal',
  path: '/jadwal',
  getParentRoute: () => DokterRoute,
} as any)
const ApiTreatmentImageRoute = ApiTreatmentImageRouteImport.update({
  id: '/api/treatment-image',
  path: '/api/treatment-image',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSeedRoute = ApiSeedRouteImport.update({
  id: '/api/seed',
  path: '/api/seed',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBootstrapOwnerRoute = ApiBootstrapOwnerRouteImport.update({
  id: '/api/bootstrap-owner',
  path: '/api/bootstrap-owner',
  getParentRoute: () => rootRouteImport,
} as any)
const AkunProfilRoute = AkunProfilRouteImport.update({
  id: '/profil',
  path: '/profil',
  getParentRoute: () => AkunRoute,
} as any)
const AkunPrivilegeRoute = AkunPrivilegeRouteImport.update({
  id: '/privilege',
  path: '/privilege',
  getParentRoute: () => AkunRoute,
} as any)
const OwnerPasienIndexRoute = OwnerPasienIndexRouteImport.update({
  id: '/pasien/',
  path: '/pasien/',
  getParentRoute: () => OwnerRoute,
} as any)
const OwnerDokterIndexRoute = OwnerDokterIndexRouteImport.update({
  id: '/dokter/',
  path: '/dokter/',
  getParentRoute: () => OwnerRoute,
} as any)
const DokterPasienIndexRoute = DokterPasienIndexRouteImport.update({
  id: '/pasien/',
  path: '/pasien/',
  getParentRoute: () => DokterRoute,
} as any)
const AkunBookingIndexRoute = AkunBookingIndexRouteImport.update({
  id: '/booking/',
  path: '/booking/',
  getParentRoute: () => AkunRoute,
} as any)
const OwnerPasienIdRoute = OwnerPasienIdRouteImport.update({
  id: '/pasien/$id',
  path: '/pasien/$id',
  getParentRoute: () => OwnerRoute,
} as any)
const OwnerDokterIdRoute = OwnerDokterIdRouteImport.update({
  id: '/dokter/$id',
  path: '/dokter/$id',
  getParentRoute: () => OwnerRoute,
} as any)
const DokterPasienIdRoute = DokterPasienIdRouteImport.update({
  id: '/pasien/$id',
  path: '/pasien/$id',
  getParentRoute: () => DokterRoute,
} as any)
const ApiMidtransNotificationRoute = ApiMidtransNotificationRouteImport.update({
  id: '/api/midtrans/notification',
  path: '/api/midtrans/notification',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AkunBookingIdRoute = AkunBookingIdRouteImport.update({
  id: '/booking/$id',
  path: '/booking/$id',
  getParentRoute: () => AkunRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/akun': typeof AkunRouteWithChildren
  '/booking': typeof BookingRoute
  '/dokter': typeof DokterRouteWithChildren
  '/keranjang': typeof KeranjangRoute
  '/lanjut': typeof LanjutRoute
  '/lengkapi-profil': typeof LengkapiProfilRoute
  '/masuk': typeof MasukRoute
  '/owner': typeof OwnerRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/tentang': typeof TentangRoute
  '/akun/privilege': typeof AkunPrivilegeRoute
  '/akun/profil': typeof AkunProfilRoute
  '/api/bootstrap-owner': typeof ApiBootstrapOwnerRoute
  '/api/health': typeof ApiHealthRoute
  '/api/seed': typeof ApiSeedRoute
  '/api/treatment-image': typeof ApiTreatmentImageRoute
  '/dokter/jadwal': typeof DokterJadwalRoute
  '/dokter/profil': typeof DokterProfilRoute
  '/kwitansi/$id': typeof KwitansiIdRoute
  '/owner/akun': typeof OwnerAkunRoute
  '/owner/beautician': typeof OwnerBeauticianRoute
  '/owner/jadwal': typeof OwnerJadwalRoute
  '/owner/laporan': typeof OwnerLaporanRoute
  '/owner/pos': typeof OwnerPosRoute
  '/owner/privilege': typeof OwnerPrivilegeRoute
  '/owner/profil': typeof OwnerProfilRoute
  '/owner/transaksi': typeof OwnerTransaksiRoute
  '/owner/treatment': typeof OwnerTreatmentRoute
  '/owner/voucher': typeof OwnerVoucherRoute
  '/treatment/$id': typeof TreatmentIdRoute
  '/akun/': typeof AkunIndexRoute
  '/dokter/': typeof DokterIndexRoute
  '/owner/': typeof OwnerIndexRoute
  '/treatment/': typeof TreatmentIndexRoute
  '/akun/booking/$id': typeof AkunBookingIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/midtrans/notification': typeof ApiMidtransNotificationRoute
  '/dokter/pasien/$id': typeof DokterPasienIdRoute
  '/owner/dokter/$id': typeof OwnerDokterIdRoute
  '/owner/pasien/$id': typeof OwnerPasienIdRoute
  '/akun/booking/': typeof AkunBookingIndexRoute
  '/dokter/pasien/': typeof DokterPasienIndexRoute
  '/owner/dokter/': typeof OwnerDokterIndexRoute
  '/owner/pasien/': typeof OwnerPasienIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/booking': typeof BookingRoute
  '/keranjang': typeof KeranjangRoute
  '/lanjut': typeof LanjutRoute
  '/lengkapi-profil': typeof LengkapiProfilRoute
  '/masuk': typeof MasukRoute
  '/reset-password': typeof ResetPasswordRoute
  '/tentang': typeof TentangRoute
  '/akun/privilege': typeof AkunPrivilegeRoute
  '/akun/profil': typeof AkunProfilRoute
  '/api/bootstrap-owner': typeof ApiBootstrapOwnerRoute
  '/api/health': typeof ApiHealthRoute
  '/api/seed': typeof ApiSeedRoute
  '/api/treatment-image': typeof ApiTreatmentImageRoute
  '/dokter/jadwal': typeof DokterJadwalRoute
  '/dokter/profil': typeof DokterProfilRoute
  '/kwitansi/$id': typeof KwitansiIdRoute
  '/owner/akun': typeof OwnerAkunRoute
  '/owner/beautician': typeof OwnerBeauticianRoute
  '/owner/jadwal': typeof OwnerJadwalRoute
  '/owner/laporan': typeof OwnerLaporanRoute
  '/owner/pos': typeof OwnerPosRoute
  '/owner/privilege': typeof OwnerPrivilegeRoute
  '/owner/profil': typeof OwnerProfilRoute
  '/owner/transaksi': typeof OwnerTransaksiRoute
  '/owner/treatment': typeof OwnerTreatmentRoute
  '/owner/voucher': typeof OwnerVoucherRoute
  '/treatment/$id': typeof TreatmentIdRoute
  '/akun': typeof AkunIndexRoute
  '/dokter': typeof DokterIndexRoute
  '/owner': typeof OwnerIndexRoute
  '/treatment': typeof TreatmentIndexRoute
  '/akun/booking/$id': typeof AkunBookingIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/midtrans/notification': typeof ApiMidtransNotificationRoute
  '/dokter/pasien/$id': typeof DokterPasienIdRoute
  '/owner/dokter/$id': typeof OwnerDokterIdRoute
  '/owner/pasien/$id': typeof OwnerPasienIdRoute
  '/akun/booking': typeof AkunBookingIndexRoute
  '/dokter/pasien': typeof DokterPasienIndexRoute
  '/owner/dokter': typeof OwnerDokterIndexRoute
  '/owner/pasien': typeof OwnerPasienIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/akun': typeof AkunRouteWithChildren
  '/booking': typeof BookingRoute
  '/dokter': typeof DokterRouteWithChildren
  '/keranjang': typeof KeranjangRoute
  '/lanjut': typeof LanjutRoute
  '/lengkapi-profil': typeof LengkapiProfilRoute
  '/masuk': typeof MasukRoute
  '/owner': typeof OwnerRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/tentang': typeof TentangRoute
  '/akun/privilege': typeof AkunPrivilegeRoute
  '/akun/profil': typeof AkunProfilRoute
  '/api/bootstrap-owner': typeof ApiBootstrapOwnerRoute
  '/api/health': typeof ApiHealthRoute
  '/api/seed': typeof ApiSeedRoute
  '/api/treatment-image': typeof ApiTreatmentImageRoute
  '/dokter/jadwal': typeof DokterJadwalRoute
  '/dokter/profil': typeof DokterProfilRoute
  '/kwitansi/$id': typeof KwitansiIdRoute
  '/owner/akun': typeof OwnerAkunRoute
  '/owner/beautician': typeof OwnerBeauticianRoute
  '/owner/jadwal': typeof OwnerJadwalRoute
  '/owner/laporan': typeof OwnerLaporanRoute
  '/owner/pos': typeof OwnerPosRoute
  '/owner/privilege': typeof OwnerPrivilegeRoute
  '/owner/profil': typeof OwnerProfilRoute
  '/owner/transaksi': typeof OwnerTransaksiRoute
  '/owner/treatment': typeof OwnerTreatmentRoute
  '/owner/voucher': typeof OwnerVoucherRoute
  '/treatment/$id': typeof TreatmentIdRoute
  '/akun/': typeof AkunIndexRoute
  '/dokter/': typeof DokterIndexRoute
  '/owner/': typeof OwnerIndexRoute
  '/treatment/': typeof TreatmentIndexRoute
  '/akun/booking/$id': typeof AkunBookingIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/midtrans/notification': typeof ApiMidtransNotificationRoute
  '/dokter/pasien/$id': typeof DokterPasienIdRoute
  '/owner/dokter/$id': typeof OwnerDokterIdRoute
  '/owner/pasien/$id': typeof OwnerPasienIdRoute
  '/akun/booking/': typeof AkunBookingIndexRoute
  '/dokter/pasien/': typeof DokterPasienIndexRoute
  '/owner/dokter/': typeof OwnerDokterIndexRoute
  '/owner/pasien/': typeof OwnerPasienIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/akun'
    | '/booking'
    | '/dokter'
    | '/keranjang'
    | '/lanjut'
    | '/lengkapi-profil'
    | '/masuk'
    | '/owner'
    | '/reset-password'
    | '/tentang'
    | '/akun/privilege'
    | '/akun/profil'
    | '/api/bootstrap-owner'
    | '/api/health'
    | '/api/seed'
    | '/api/treatment-image'
    | '/dokter/jadwal'
    | '/dokter/profil'
    | '/kwitansi/$id'
    | '/owner/akun'
    | '/owner/beautician'
    | '/owner/jadwal'
    | '/owner/laporan'
    | '/owner/pos'
    | '/owner/privilege'
    | '/owner/profil'
    | '/owner/transaksi'
    | '/owner/treatment'
    | '/owner/voucher'
    | '/treatment/$id'
    | '/akun/'
    | '/dokter/'
    | '/owner/'
    | '/treatment/'
    | '/akun/booking/$id'
    | '/api/auth/$'
    | '/api/midtrans/notification'
    | '/dokter/pasien/$id'
    | '/owner/dokter/$id'
    | '/owner/pasien/$id'
    | '/akun/booking/'
    | '/dokter/pasien/'
    | '/owner/dokter/'
    | '/owner/pasien/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/booking'
    | '/keranjang'
    | '/lanjut'
    | '/lengkapi-profil'
    | '/masuk'
    | '/reset-password'
    | '/tentang'
    | '/akun/privilege'
    | '/akun/profil'
    | '/api/bootstrap-owner'
    | '/api/health'
    | '/api/seed'
    | '/api/treatment-image'
    | '/dokter/jadwal'
    | '/dokter/profil'
    | '/kwitansi/$id'
    | '/owner/akun'
    | '/owner/beautician'
    | '/owner/jadwal'
    | '/owner/laporan'
    | '/owner/pos'
    | '/owner/privilege'
    | '/owner/profil'
    | '/owner/transaksi'
    | '/owner/treatment'
    | '/owner/voucher'
    | '/treatment/$id'
    | '/akun'
    | '/dokter'
    | '/owner'
    | '/treatment'
    | '/akun/booking/$id'
    | '/api/auth/$'
    | '/api/midtrans/notification'
    | '/dokter/pasien/$id'
    | '/owner/dokter/$id'
    | '/owner/pasien/$id'
    | '/akun/booking'
    | '/dokter/pasien'
    | '/owner/dokter'
    | '/owner/pasien'
  id:
    | '__root__'
    | '/'
    | '/akun'
    | '/booking'
    | '/dokter'
    | '/keranjang'
    | '/lanjut'
    | '/lengkapi-profil'
    | '/masuk'
    | '/owner'
    | '/reset-password'
    | '/tentang'
    | '/akun/privilege'
    | '/akun/profil'
    | '/api/bootstrap-owner'
    | '/api/health'
    | '/api/seed'
    | '/api/treatment-image'
    | '/dokter/jadwal'
    | '/dokter/profil'
    | '/kwitansi/$id'
    | '/owner/akun'
    | '/owner/beautician'
    | '/owner/jadwal'
    | '/owner/laporan'
    | '/owner/pos'
    | '/owner/privilege'
    | '/owner/profil'
    | '/owner/transaksi'
    | '/owner/treatment'
    | '/owner/voucher'
    | '/treatment/$id'
    | '/akun/'
    | '/dokter/'
    | '/owner/'
    | '/treatment/'
    | '/akun/booking/$id'
    | '/api/auth/$'
    | '/api/midtrans/notification'
    | '/dokter/pasien/$id'
    | '/owner/dokter/$id'
    | '/owner/pasien/$id'
    | '/akun/booking/'
    | '/dokter/pasien/'
    | '/owner/dokter/'
    | '/owner/pasien/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AkunRoute: typeof AkunRouteWithChildren
  BookingRoute: typeof BookingRoute
  DokterRoute: typeof DokterRouteWithChildren
  KeranjangRoute: typeof KeranjangRoute
  LanjutRoute: typeof LanjutRoute
  LengkapiProfilRoute: typeof LengkapiProfilRoute
  MasukRoute: typeof MasukRoute
  OwnerRoute: typeof OwnerRouteWithChildren
  ResetPasswordRoute: typeof ResetPasswordRoute
  TentangRoute: typeof TentangRoute
  ApiBootstrapOwnerRoute: typeof ApiBootstrapOwnerRoute
  ApiHealthRoute: typeof ApiHealthRoute
  ApiSeedRoute: typeof ApiSeedRoute
  ApiTreatmentImageRoute: typeof ApiTreatmentImageRoute
  KwitansiIdRoute: typeof KwitansiIdRoute
  TreatmentIdRoute: typeof TreatmentIdRoute
  TreatmentIndexRoute: typeof TreatmentIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiMidtransNotificationRoute: typeof ApiMidtransNotificationRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tentang': {
      id: '/tentang'
      path: '/tentang'
      fullPath: '/tentang'
      preLoaderRoute: typeof TentangRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/owner': {
      id: '/owner'
      path: '/owner'
      fullPath: '/owner'
      preLoaderRoute: typeof OwnerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/masuk': {
      id: '/masuk'
      path: '/masuk'
      fullPath: '/masuk'
      preLoaderRoute: typeof MasukRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lengkapi-profil': {
      id: '/lengkapi-profil'
      path: '/lengkapi-profil'
      fullPath: '/lengkapi-profil'
      preLoaderRoute: typeof LengkapiProfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lanjut': {
      id: '/lanjut'
      path: '/lanjut'
      fullPath: '/lanjut'
      preLoaderRoute: typeof LanjutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/keranjang': {
      id: '/keranjang'
      path: '/keranjang'
      fullPath: '/keranjang'
      preLoaderRoute: typeof KeranjangRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dokter': {
      id: '/dokter'
      path: '/dokter'
      fullPath: '/dokter'
      preLoaderRoute: typeof DokterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/booking': {
      id: '/booking'
      path: '/booking'
      fullPath: '/booking'
      preLoaderRoute: typeof BookingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/akun': {
      id: '/akun'
      path: '/akun'
      fullPath: '/akun'
      preLoaderRoute: typeof AkunRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/treatment/': {
      id: '/treatment/'
      path: '/treatment'
      fullPath: '/treatment/'
      preLoaderRoute: typeof TreatmentIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/owner/': {
      id: '/owner/'
      path: '/'
      fullPath: '/owner/'
      preLoaderRoute: typeof OwnerIndexRouteImport
      parentRoute: typeof OwnerRoute
    }
    '/dokter/': {
      id: '/dokter/'
      path: '/'
      fullPath: '/dokter/'
      preLoaderRoute: typeof DokterIndexRouteImport
      parentRoute: typeof DokterRoute
    }
    '/akun/': {
      id: '/akun/'
      path: '/'
      fullPath: '/akun/'
      preLoaderRoute: typeof AkunIndexRouteImport
      parentRoute: typeof AkunRoute
    }
    '/treatment/$id': {
      id: '/treatment/$id'
      path: '/treatment/$id'
      fullPath: '/treatment/$id'
      preLoaderRoute: typeof TreatmentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/owner/voucher': {
      id: '/owner/voucher'
      path: '/voucher'
      fullPath: '/owner/voucher'
      preLoaderRoute: typeof OwnerVoucherRouteImport
      parentRoute: typeof OwnerRoute
    }
    '/owner/treatment': {
      id: '/owner/treatment'
      path: '/treatment'
      fullPath: '/owner/treatment'
      preLoaderRoute: typeof OwnerTreatmentRouteImport
      parentRoute: typeof OwnerRoute
    }
    '/owner/transaksi': {
      id: '/owner/transaksi'
      path: '/transaksi'
      fullPath: '/owner/transaksi'
      preLoaderRoute: typeof OwnerTransaksiRouteImport
      parentRoute: typeof OwnerRoute
    }
    '/owner/profil': {
      id: '/owner/profil'
      path: '/profil'
      fullPath: '/owner/profil'
      preLoaderRoute: typeof OwnerProfilRouteImport
      parentRoute: typeof OwnerRoute
    }
    '/owner/privilege': {
      id: '/owner/privilege'
      path: '/privilege'
      fullPath: '/owner/privilege'
      preLoaderRoute: typeof OwnerPrivilegeRouteImport
      parentRoute: typeof OwnerRoute
    }
    '/owner/pos': {
      id: '/owner/pos'
      path: '/pos'
      fullPath: '/owner/pos'
      preLoaderRoute: typeof OwnerPosRouteImport
      parentRoute: typeof OwnerRoute
    }
    '/owner/laporan': {
      id: '/owner/laporan'
      path: '/laporan'
      fullPath: '/owner/laporan'
      preLoaderRoute: typeof OwnerLaporanRouteImport
      parentRoute: typeof OwnerRoute
    }
    '/owner/jadwal': {
      id: '/owner/jadwal'
      path: '/jadwal'
      fullPath: '/owner/jadwal'
      preLoaderRoute: typeof OwnerJadwalRouteImport
      parentRoute: typeof OwnerRoute
    }
    '/owner/beautician': {
      id: '/owner/beautician'
      path: '/beautician'
      fullPath: '/owner/beautician'
      preLoaderRoute: typeof OwnerBeauticianRouteImport
      parentRoute: typeof OwnerRoute
    }
    '/owner/akun': {
      id: '/owner/akun'
      path: '/akun'
      fullPath: '/owner/akun'
      preLoaderRoute: typeof OwnerAkunRouteImport
      parentRoute: typeof OwnerRoute
    }
    '/kwitansi/$id': {
      id: '/kwitansi/$id'
      path: '/kwitansi/$id'
      fullPath: '/kwitansi/$id'
      preLoaderRoute: typeof KwitansiIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dokter/profil': {
      id: '/dokter/profil'
      path: '/profil'
      fullPath: '/dokter/profil'
      preLoaderRoute: typeof DokterProfilRouteImport
      parentRoute: typeof DokterRoute
    }
    '/dokter/jadwal': {
      id: '/dokter/jadwal'
      path: '/jadwal'
      fullPath: '/dokter/jadwal'
      preLoaderRoute: typeof DokterJadwalRouteImport
      parentRoute: typeof DokterRoute
    }
    '/api/treatment-image': {
      id: '/api/treatment-image'
      path: '/api/treatment-image'
      fullPath: '/api/treatment-image'
      preLoaderRoute: typeof ApiTreatmentImageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/seed': {
      id: '/api/seed'
      path: '/api/seed'
      fullPath: '/api/seed'
      preLoaderRoute: typeof ApiSeedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/bootstrap-owner': {
      id: '/api/bootstrap-owner'
      path: '/api/bootstrap-owner'
      fullPath: '/api/bootstrap-owner'
      preLoaderRoute: typeof ApiBootstrapOwnerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/akun/profil': {
      id: '/akun/profil'
      path: '/profil'
      fullPath: '/akun/profil'
      preLoaderRoute: typeof AkunProfilRouteImport
      parentRoute: typeof AkunRoute
    }
    '/akun/privilege': {
      id: '/akun/privilege'
      path: '/privilege'
      fullPath: '/akun/privilege'
      preLoaderRoute: typeof AkunPrivilegeRouteImport
      parentRoute: typeof AkunRoute
    }
    '/owner/pasien/': {
      id: '/owner/pasien/'
      path: '/pasien'
      fullPath: '/owner/pasien/'
      preLoaderRoute: typeof OwnerPasienIndexRouteImport
      parentRoute: typeof OwnerRoute
    }
    '/owner/dokter/': {
      id: '/owner/dokter/'
      path: '/dokter'
      fullPath: '/owner/dokter/'
      preLoaderRoute: typeof OwnerDokterIndexRouteImport
      parentRoute: typeof OwnerRoute
    }
    '/dokter/pasien/': {
      id: '/dokter/pasien/'
      path: '/pasien'
      fullPath: '/dokter/pasien/'
      preLoaderRoute: typeof DokterPasienIndexRouteImport
      parentRoute: typeof DokterRoute
    }
    '/akun/booking/': {
      id: '/akun/booking/'
      path: '/booking'
      fullPath: '/akun/booking/'
      preLoaderRoute: typeof AkunBookingIndexRouteImport
      parentRoute: typeof AkunRoute
    }
    '/owner/pasien/$id': {
      id: '/owner/pasien/$id'
      path: '/pasien/$id'
      fullPath: '/owner/pasien/$id'
      preLoaderRoute: typeof OwnerPasienIdRouteImport
      parentRoute: typeof OwnerRoute
    }
    '/owner/dokter/$id': {
      id: '/owner/dokter/$id'
      path: '/dokter/$id'
      fullPath: '/owner/dokter/$id'
      preLoaderRoute: typeof OwnerDokterIdRouteImport
      parentRoute: typeof OwnerRoute
    }
    '/dokter/pasien/$id': {
      id: '/dokter/pasien/$id'
      path: '/pasien/$id'
      fullPath: '/dokter/pasien/$id'
      preLoaderRoute: typeof DokterPasienIdRouteImport
      parentRoute: typeof DokterRoute
    }
    '/api/midtrans/notification': {
      id: '/api/midtrans/notification'
      path: '/api/midtrans/notification'
      fullPath: '/api/midtrans/notification'
      preLoaderRoute: typeof ApiMidtransNotificationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/akun/booking/$id': {
      id: '/akun/booking/$id'
      path: '/booking/$id'
      fullPath: '/akun/booking/$id'
      preLoaderRoute: typeof AkunBookingIdRouteImport
      parentRoute: typeof AkunRoute
    }
  }
}

interface AkunRouteChildren {
  AkunPrivilegeRoute: typeof AkunPrivilegeRoute
  AkunProfilRoute: typeof AkunProfilRoute
  AkunIndexRoute: typeof AkunIndexRoute
  AkunBookingIdRoute: typeof AkunBookingIdRoute
  AkunBookingIndexRoute: typeof AkunBookingIndexRoute
}

const AkunRouteChildren: AkunRouteChildren = {
  AkunPrivilegeRoute: AkunPrivilegeRoute,
  AkunProfilRoute: AkunProfilRoute,
  AkunIndexRoute: AkunIndexRoute,
  AkunBookingIdRoute: AkunBookingIdRoute,
  AkunBookingIndexRoute: AkunBookingIndexRoute,
}

const AkunRouteWithChildren = AkunRoute._addFileChildren(AkunRouteChildren)

interface DokterRouteChildren {
  DokterJadwalRoute: typeof DokterJadwalRoute
  DokterProfilRoute: typeof DokterProfilRoute
  DokterIndexRoute: typeof DokterIndexRoute
  DokterPasienIdRoute: typeof DokterPasienIdRoute
  DokterPasienIndexRoute: typeof DokterPasienIndexRoute
}

const DokterRouteChildren: DokterRouteChildren = {
  DokterJadwalRoute: DokterJadwalRoute,
  DokterProfilRoute: DokterProfilRoute,
  DokterIndexRoute: DokterIndexRoute,
  DokterPasienIdRoute: DokterPasienIdRoute,
  DokterPasienIndexRoute: DokterPasienIndexRoute,
}

const DokterRouteWithChildren =
  DokterRoute._addFileChildren(DokterRouteChildren)

interface OwnerRouteChildren {
  OwnerAkunRoute: typeof OwnerAkunRoute
  OwnerBeauticianRoute: typeof OwnerBeauticianRoute
  OwnerJadwalRoute: typeof OwnerJadwalRoute
  OwnerLaporanRoute: typeof OwnerLaporanRoute
  OwnerPosRoute: typeof OwnerPosRoute
  OwnerPrivilegeRoute: typeof OwnerPrivilegeRoute
  OwnerProfilRoute: typeof OwnerProfilRoute
  OwnerTransaksiRoute: typeof OwnerTransaksiRoute
  OwnerTreatmentRoute: typeof OwnerTreatmentRoute
  OwnerVoucherRoute: typeof OwnerVoucherRoute
  OwnerIndexRoute: typeof OwnerIndexRoute
  OwnerDokterIdRoute: typeof OwnerDokterIdRoute
  OwnerPasienIdRoute: typeof OwnerPasienIdRoute
  OwnerDokterIndexRoute: typeof OwnerDokterIndexRoute
  OwnerPasienIndexRoute: typeof OwnerPasienIndexRoute
}

const OwnerRouteChildren: OwnerRouteChildren = {
  OwnerAkunRoute: OwnerAkunRoute,
  OwnerBeauticianRoute: OwnerBeauticianRoute,
  OwnerJadwalRoute: OwnerJadwalRoute,
  OwnerLaporanRoute: OwnerLaporanRoute,
  OwnerPosRoute: OwnerPosRoute,
  OwnerPrivilegeRoute: OwnerPrivilegeRoute,
  OwnerProfilRoute: OwnerProfilRoute,
  OwnerTransaksiRoute: OwnerTransaksiRoute,
  OwnerTreatmentRoute: OwnerTreatmentRoute,
  OwnerVoucherRoute: OwnerVoucherRoute,
  OwnerIndexRoute: OwnerIndexRoute,
  OwnerDokterIdRoute: OwnerDokterIdRoute,
  OwnerPasienIdRoute: OwnerPasienIdRoute,
  OwnerDokterIndexRoute: OwnerDokterIndexRoute,
  OwnerPasienIndexRoute: OwnerPasienIndexRoute,
}

const OwnerRouteWithChildren = OwnerRoute._addFileChildren(OwnerRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AkunRoute: AkunRouteWithChildren,
  BookingRoute: BookingRoute,
  DokterRoute: DokterRouteWithChildren,
  KeranjangRoute: KeranjangRoute,
  LanjutRoute: LanjutRoute,
  LengkapiProfilRoute: LengkapiProfilRoute,
  MasukRoute: MasukRoute,
  OwnerRoute: OwnerRouteWithChildren,
  ResetPasswordRoute: ResetPasswordRoute,
  TentangRoute: TentangRoute,
  ApiBootstrapOwnerRoute: ApiBootstrapOwnerRoute,
  ApiHealthRoute: ApiHealthRoute,
  ApiSeedRoute: ApiSeedRoute,
  ApiTreatmentImageRoute: ApiTreatmentImageRoute,
  KwitansiIdRoute: KwitansiIdRoute,
  TreatmentIdRoute: TreatmentIdRoute,
  TreatmentIndexRoute: TreatmentIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiMidtransNotificationRoute: ApiMidtransNotificationRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
